"use client";

import { useEffect, useLayoutEffect, useRef, useState, type CSSProperties, type ReactNode, type RefObject } from "react";
import { useTranslation } from "@/lib/language-context";
import type { Round, Team } from "@/lib/match13/types";
import { isTrueBye, resolvedTeams, winnerLoserOf, type BracketMatch } from "@/lib/match13/poules";
import { computeStandings, type StandingRow } from "@/lib/match13/standings";

// Gedeelde weergave van de poule-schema's en de knock-outpiramide: gebruikt
// door de app zelf (Match13App.tsx, mét invoer) en door de publieke
// live-pagina (Match13LiveView.tsx, enkel kijken).

// Live speeltijd per wedstrijd: tikt op (groen) zolang er geen score staat,
// bevriest (rood) zodra de score volledig is ingevuld.
export function MatchTimer({ startedAt, finishedAt }: { startedAt: number; finishedAt?: number }) {
  const [now, setNow] = useState(() => Date.now());

  useEffect(() => {
    if (finishedAt) return;
    const id = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(id);
  }, [finishedAt]);

  const totalSeconds = Math.max(0, Math.floor(((finishedAt ?? now) - startedAt) / 1000));
  const mm = Math.floor(totalSeconds / 60);
  const ss = totalSeconds % 60;

  return (
    <span className={"match-timer" + (finishedAt ? " klaar" : " bezig")}>
      {mm}:{String(ss).padStart(2, "0")}
    </span>
  );
}

// A poule of 4's mini-bracket, or the knock-out pyramid — rendered as
// columns (one per round) with each match showing "?" for a side that isn't
// known yet, live score inputs once both sides are, and the winner
// highlighted once it's played. Editing is always allowed (even on an
// already-decided match) so a wrong score can be fixed at any point.
//
// The round/label text baked into each match (Ronde 1, Winnaars, Verliezers,
// Barrage, Vrij geloot — from lib/match13/poules.ts) stays Dutch for now:
// it's generated by the shared, already-tested scheduling engine, and
// localizing it would mean teaching that pure logic about language. Most of
// these are petanque terms a French speaker already recognizes ("barrage").
// Rechte gouden verbindingslijntjes tussen een wedstrijd en de 1 of 2
// wedstrijden waaruit die voortkomt (sourceA/sourceB) — enkel gebruikt in de
// knock-outpiramide (via `showConnectors`), waar dat een echt boompje vormt.
// Berekend op basis van de werkelijke positie van elke kaart op het scherm
// (niet aangenomen op vaste hoogtes) zodat het klopt ongeacht tekstlengte,
// een gestarte klok, enz. — en enkel op een scherm breed genoeg om de
// kolommen naast elkaar te tonen (zie de mobiele weergave hierboven).
function BracketConnectors({
  matches,
  containerRef,
  nodeRefs,
  version,
}: {
  matches: BracketMatch[];
  containerRef: RefObject<HTMLDivElement | null>;
  nodeRefs: RefObject<Map<string, HTMLDivElement>>;
  version: number;
}) {
  const [paths, setPaths] = useState<string[]>([]);
  const [size, setSize] = useState({ width: 0, height: 0 });

  useLayoutEffect(() => {
    function bereken() {
      const container = containerRef.current;
      // Moet gelijk lopen met het @media (max-width: 900px)-breakpoint in
      // match13.css dat de kolommen onder elkaar zet — anders proberen we
      // hier lijnen te tekenen tussen kaartjes die intussen gestapeld staan.
      if (!container || window.innerWidth <= 900) {
        setPaths([]);
        return;
      }
      const containerBox = container.getBoundingClientRect();
      const nieuwePaths: string[] = [];
      for (const m of matches) {
        const doelEl = nodeRefs.current?.get(m.id);
        if (!doelEl) continue;
        const doelBox = doelEl.getBoundingClientRect();
        const doelY = doelBox.top + doelBox.height / 2 - containerBox.top;
        const doelX = doelBox.left - containerBox.left;
        for (const bron of [m.sourceA, m.sourceB]) {
          if (!bron) continue;
          const bronEl = nodeRefs.current?.get(bron.matchId);
          if (!bronEl) continue;
          const bronBox = bronEl.getBoundingClientRect();
          const bronY = bronBox.top + bronBox.height / 2 - containerBox.top;
          const bronX = bronBox.right - containerBox.left;
          const middenX = bronX + (doelX - bronX) / 2;
          nieuwePaths.push(`M ${bronX} ${bronY} H ${middenX} V ${doelY} H ${doelX}`);
        }
      }
      setPaths(nieuwePaths);
      setSize({ width: container.scrollWidth, height: container.scrollHeight });
    }
    bereken();
    window.addEventListener("resize", bereken);
    const observer = new ResizeObserver(bereken);
    if (containerRef.current) observer.observe(containerRef.current);
    return () => {
      window.removeEventListener("resize", bereken);
      observer.disconnect();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [matches, version]);

  if (paths.length === 0) return null;
  return (
    <svg className="bracket-connectors" width={size.width} height={size.height}>
      {paths.map((d, i) => (
        <path key={i} d={d} />
      ))}
    </svg>
  );
}

export function BracketColumns({
  matches,
  numNameOf,
  editable,
  onScore,
  onWin,
  onClear,
  onCourtChange,
  onStart,
  accent,
  simpleWinLoss,
  showConnectors,
}: {
  matches: BracketMatch[];
  numNameOf: (id: string | null) => ReactNode;
  editable?: boolean;
  onScore?: (matchId: string, side: "scoreA" | "scoreB", value: string) => void;
  onWin?: (matchId: string, kant: "A" | "B") => void;
  onClear?: (matchId: string) => void;
  onCourtChange?: (matchId: string, court: number) => void;
  onStart?: (matchId: string) => void;
  accent?: string;
  // Poule-wedstrijden tellen enkel wie doorgaat, geen echte eindstand — geen
  // scores intikken dus, gewoon "wint"-knoppen per kant. scoreA/scoreB
  // worden dan onder de motorkap wel gezet (1 tegen 0), maar die getallen
  // betekenen niets buiten "wie won" en worden dus ook nooit getoond.
  simpleWinLoss?: boolean;
  // Tekent gouden lijntjes tussen elke wedstrijd en waar die vandaan komt —
  // enkel zinvol voor de knock-outpiramide (zie BracketConnectors hierboven).
  showConnectors?: boolean;
}) {
  const { t } = useTranslation();
  const rounds = Array.from(new Set(matches.map((m) => m.round))).sort((a, b) => a - b);
  const containerRef = useRef<HTMLDivElement>(null);
  const nodeRefs = useRef(new Map<string, HTMLDivElement>());
  // Verandert bij elke render zodat BracketConnectors herberekent na een
  // wijziging in de inhoud (score ingevuld, klok gestart, ...) die de hoogte
  // van een kaart kan doen veranderen, zonder de volledige matches-array zelf
  // als dependency te moeten vergelijken.
  const renderTeller = useRef(0);
  renderTeller.current += 1;

  return (
    <div
      className="bracket"
      ref={containerRef}
      style={accent ? ({ "--poule-accent": accent } as CSSProperties) : undefined}
    >
      {showConnectors && (
        <BracketConnectors
          matches={matches}
          containerRef={containerRef}
          nodeRefs={nodeRefs}
          version={renderTeller.current}
        />
      )}
      {rounds.map((r) => (
        <div className="bracket-col" key={r}>
          {matches
            .filter((m) => m.round === r)
            .map((m) => {
              const [a, b] = resolvedTeams(matches, m);
              const bye = isTrueBye(m);
              const ready = a !== null && b !== null;
              const done = m.scoreA !== undefined && m.scoreB !== undefined;
              const aWon = done && m.scoreA! > m.scoreB!;
              const bWon = done && m.scoreB! > m.scoreA!;
              const isFinale = m.label === "Finale";
              return (
                <div
                  className={"bracket-match" + (done ? " done" : ready ? " ready" : " pending") + (isFinale ? " finale" : "")}
                  key={m.id}
                  ref={(el) => {
                    if (el) nodeRefs.current.set(m.id, el);
                    else nodeRefs.current.delete(m.id);
                  }}
                >
                  {isFinale && (
                    <div className="bracket-finale-banner">
                      <span className="bracket-finale-icoon">🏆</span>
                      <span className="bracket-finale-titel">{t.match13.finaleLabel}</span>
                    </div>
                  )}
                  <div className={"bracket-match-label" + (isFinale ? " centered" : "")}>
                    {isFinale ? null : m.label}
                    {!bye && m.court ? (
                      editable && onCourtChange ? (
                        <span className="bracket-plein-edit">
                          {isFinale ? "" : " — "}
                          {t.match13.pleinLabelKort}{" "}
                          <input
                            type="number"
                            min={1}
                            className="bracket-plein-input"
                            value={m.court}
                            onChange={(e) => onCourtChange(m.id, Math.max(1, Number(e.target.value) || 1))}
                          />
                        </span>
                      ) : (
                        `${isFinale ? "" : " — "}${t.match13.plein(m.court)}`
                      )
                    ) : (
                      ""
                    )}
                  </div>
                  {!bye && ready && (m.startedAt || (editable && onStart && !done)) && (
                    <div className="bracket-timer-row">
                      {m.startedAt ? (
                        <MatchTimer startedAt={m.startedAt} finishedAt={m.finishedAt} />
                      ) : (
                        <button className="bracket-start-btn" onClick={() => onStart!(m.id)}>
                          {t.match13.startKnop}
                        </button>
                      )}
                    </div>
                  )}
                  <div className={"bracket-side" + (aWon ? " winner" : bWon ? " loser" : "")}>
                    <span className="bracket-name">{a ? numNameOf(a) : "?"}</span>
                    {simpleWinLoss ? (
                      editable && ready && !done && (
                        <button className="bracket-win-btn" onClick={() => onWin?.(m.id, "A")}>
                          {t.match13.wintKnop}
                        </button>
                      )
                    ) : editable && ready ? (
                      <input
                        type="number"
                        min={0}
                        max={13}
                        value={m.scoreA ?? ""}
                        onChange={(e) => onScore?.(m.id, "scoreA", e.target.value)}
                      />
                    ) : (
                      done && <span className="bracket-score">{m.scoreA}</span>
                    )}
                  </div>
                  {!bye && (
                    <div className={"bracket-side" + (bWon ? " winner" : aWon ? " loser" : "")}>
                      <span className="bracket-name">{b ? numNameOf(b) : "?"}</span>
                      {simpleWinLoss ? (
                        editable && ready && !done && (
                          <button className="bracket-win-btn" onClick={() => onWin?.(m.id, "B")}>
                            {t.match13.wintKnop}
                          </button>
                        )
                      ) : editable && ready ? (
                        <input
                          type="number"
                          min={0}
                          max={13}
                          value={m.scoreB ?? ""}
                          onChange={(e) => onScore?.(m.id, "scoreB", e.target.value)}
                        />
                      ) : (
                        done && <span className="bracket-score">{m.scoreB}</span>
                      )}
                    </div>
                  )}
                  {bye && <div className="bracket-side bye-side">{t.match13.bye.toLowerCase()}</div>}
                  {editable && done && (
                    <button className="link-btn bracket-clear" onClick={() => onClear?.(m.id)}>
                      {t.match13.wisScore}
                    </button>
                  )}
                </div>
              );
            })}
        </div>
      ))}
    </div>
  );
}

// Een klein Petanque13-gebrand kopje boven de knock-outpiramide (Finale,
// Halve finale, ...) — zelfde opzet (logo + gouden lijn) als de kop op de
// afdrukbladen, zodat dit deel van het scherm er ook wat feestelijker uitziet
// dan een kale grijze titel.
export function PiramideKop({ label }: { label: string }) {
  return (
    <div className="piramide-kop">
      <img className="piramide-kop-logo" src="/images/logo-icon.png" alt="" />
      <h3 className="piramide-titel">{label}</h3>
    </div>
  );
}

// De donkere kaartjes (poules + knock-out) krijgen zo hun eigen Petanque13-
// merktekens: een klein rond embleem rechtsboven, en dezelfde "Gemaakt door
// Petanque13"-badge als de paginavoet, maar dan rechtsonder in het kaartje
// zelf — zichtbaar zowel op het scherm als op "Dit scherm afdrukken".
export function BracketDonkerBlok({ children, style }: { children: ReactNode; style?: CSSProperties }) {
  const { t } = useTranslation();
  return (
    <div className="bracket-donker-blok" style={style}>
      <img className="bracket-donker-embleem" src="/images/logo-icon.png" alt="" />
      {children}
      <a
        className="bracket-donker-credit"
        href="https://petanque13.be"
        target="_blank"
        rel="noopener noreferrer"
      >
        <img src="/images/logo-icon.png" alt="" />
        <span>
          {t.match13.gemaaktDoor} petanque13.be
        </span>
      </a>
    </div>
  );
}

// A small "who's through" callout next to a poule-of-4's mini-bracket — the
// direct winner is already known as soon as the Winnaars match is played
// (even before the barrage decides the 2nd spot), so this fills in as soon
// as each half is decided rather than waiting for the whole poule.
export function PouleQualifiersBadge({
  matches,
  numNameOf,
  accent,
}: {
  matches: BracketMatch[];
  numNameOf: (id: string | null) => ReactNode;
  accent?: string;
}) {
  const { t } = useTranslation();
  const poule = matches.find((m) => m.poule)?.poule;
  if (!poule) return null;
  const winner = winnerLoserOf(matches, `${poule}-WIN`, "winner");
  const barrageWinner = winnerLoserOf(matches, `${poule}-BAR`, "winner");
  return (
    <div className="poule-qualifiers" style={accent ? ({ "--poule-accent": accent } as CSSProperties) : undefined}>
      <div className="poule-qualifiers-title">{t.match13.doorNaarPiramide}</div>
      <div className="poule-qualifier-row">
        <span className="poule-qualifier-rank">1</span>
        <span>{winner ? numNameOf(winner) : t.match13.nogTeBepalen}</span>
      </div>
      <div className="poule-qualifier-row">
        <span className="poule-qualifier-rank">2</span>
        <span>{barrageWinner ? numNameOf(barrageWinner) : t.match13.nogTeBepalenBarrage}</span>
      </div>
    </div>
  );
}

// The round-robin fallback pool (size 3, or the rare n=5 single-pool case)
// has no bracket shape, so on top of its BracketColumns match list we also
// show a plain ranking table — matchpunten then saldo, same as everywhere else.
export function PouleStandingsTable({ rows }: { rows: StandingRow[] }) {
  const { t } = useTranslation();
  return (
    <div className="tabel-scroll" style={{ marginTop: "0.6rem" }}>
    <table className="standings">
      <thead>
        <tr>
          <th></th>
          <th>{t.match13.teamKolom}</th>
          <th className="num">{t.match13.gespeeld}</th>
          <th className="num">{t.match13.overwinningen}</th>
          <th className="num">{t.match13.pntVoor}</th>
          <th className="num">{t.match13.pntTegen}</th>
          <th className="num">{t.match13.saldo}</th>
        </tr>
      </thead>
      <tbody>
        {rows.map((row, i) => (
          <tr key={row.teamId}>
            <td>{i + 1}</td>
            <td className="team-name">
              <div className="team-cell">
                <span className="team-num">{row.number}</span>
                <span>{row.name}</span>
              </div>
            </td>
            <td className="num">{row.gespeeld}</td>
            <td className="num">{row.overwinningen}</td>
            <td className="num">{row.puntenVoor}</td>
            <td className="num">{row.puntenTegen}</td>
            <td className="num">{row.saldo > 0 ? `+${row.saldo}` : row.saldo}</td>
          </tr>
        ))}
      </tbody>
    </table>
    </div>
  );
}

export function roundRobinStandings(pouleTeams: Team[], pouleMatches: BracketMatch[]): StandingRow[] {
  const fakeRound: Round = {
    number: 1,
    matches: pouleMatches.map((m) => ({
      court: 0,
      teamA: m.teamA as string,
      teamB: m.teamB,
      scoreA: m.scoreA,
      scoreB: m.scoreB,
    })),
  };
  return computeStandings(pouleTeams, [fakeRound]);
}

// Wie zit er in deze poule? Zonder dit moest je de teams zelf afleiden uit de
// wedstrijdkaartjes — een rij met alle teams bovenaan de poule maakt in één
// oogopslag duidelijk wie er meespeelt.
export function PouleTeamsRij({ teams, numNameOf }: { teams: Team[]; numNameOf: (id: string | null) => ReactNode }) {
  const gesorteerd = [...teams].sort((a, b) => a.number - b.number);
  return (
    <div className="poule-teams-rij">
      {gesorteerd.map((team) => (
        <span className="poule-team-chip" key={team.id}>
          {numNameOf(team.id)}
        </span>
      ))}
    </div>
  );
}
