-- PetanQ - Waalse clubs met officieel adres en e-mailadres, aangeleverd door
-- Frederic via de FBFP-bron "SIGNALETIQUES CLUBS" (2026-07-08).
-- Provincie afgeleid uit de postcode (Brussel <1300, Waals-Brabant >=1300 voor
-- de gecombineerde BWBC-federatiecode); regio wordt automatisch afgeleid door
-- de bestaande trigger.

insert into clubs (naam, gemeente, provincie, adres, contact_email)
values
  ('La Petanque Belgradoise', 'Belgrade', 'namen', 'rue des Tautis, 1, 5020 Belgrade', 'd09@fbfp.be'),
  ('La Boule Anthisnoise ASBL', 'Anthisnes', 'luik', 'rue de la Libération, 1, 4160 Anthisnes', 'b32@fbfp.be'),
  ('Petanque Club Genval', 'Genval', 'waals-brabant', 'rue de la Fontaine, 3, 1332 Genval', 'a02@fbfp.be'),
  ('La Wavrienne', 'Wavre', 'waals-brabant', 'Avenue du Centre Sportif, 20, 1300 Wavre', 'a05@fbfp.be'),
  ('Royal Petanque Uccle Centre', 'Uccle', 'brussel', 'rue Robert Scott, 14, 1180 Uccle', 'a08@fbfp.be'),
  ('New Ixelles', 'Bruxelles', 'brussel', 'rue des Brebis, 48, 1050 Bruxelles', 'a09@fbfp.be'),
  ('Forever Saint Josse', 'Evere', 'brussel', 'Avenue des Communautés, 6, 1140 Evere', 'a10@fbfp.be'),
  ('La Petanque Jauchoise', 'Orp-Jauche', 'waals-brabant', 'Ruelle du Cuvé, 2, 1350 Orp-Jauche', 'a12@fbfp.be'),
  ('Royal Blanc Ry Ottignies', 'Louvain-La-Neuve', 'waals-brabant', 'Bld Baudouin 1er, 1348 Louvain-La-Neuve', 'a13@fbfp.be'),
  ('Royal PC Floreal', 'Bruxelles', 'brussel', 'Avenue des Nymphes 1a, 1170 Bruxelles', 'a14@fbfp.be'),
  ('Amicale Anderlechtoise P.c.', 'Anderlecht', 'brussel', 'Dreve Olympique, 60, 1070 Anderlecht', 'a17@fbfp.be'),
  ('Pétanque Auderghem Sainte Anne (p.a.s.a.)', 'Auderghem', 'brussel', 'rue du Vieux Moulin, 23, 1160 Auderghem', 'a18@fbfp.be'),
  ('Royal Petanque Club Nivelloise', 'Nivelles', 'waals-brabant', 'Chaussée de Bruxelles, 91b, 1400 Nivelles', 'a19@fbfp.be'),
  ('Kiki Tubizien', 'Tubize', 'waals-brabant', 'Chemin Massart, 66a, 1480 Tubize', 'a21@fbfp.be'),
  ('Royale P.u.s.', 'Bruxelles', 'brussel', 'rue Zwartebeek, 21, 1180 Bruxelles', 'a23@fbfp.be'),
  ('As Beauchamp', 'Limal', 'waals-brabant', 'Place de la Constellation, 3, 1300 Limal', 'a24@fbfp.be'),
  ('Royal Petanque Club La Hulpe', 'La Hulpe', 'waals-brabant', 'Avenue René Soyer, 7, 1310 La Hulpe', 'a25@fbfp.be'),
  ('Royal Petanque Club Le Frankveld ASBL', 'Bruxelles', 'brussel', 'Bd de la 2ème Armée Britannique, 520, 1190 Bruxelles', 'a27@fbfp.be'),
  ('Royal PC Paradis', 'Braine-L''Alleud', 'waals-brabant', 'rue Ernest Laurent 215, 1420 Braine-L''Alleud', 'a28@fbfp.be'),
  ('PC Le Domaine', 'Bruxelles', 'brussel', 'rue Robert Scott, 14, 1180 Bruxelles', 'a29@fbfp.be'),
  ('Royal PC Joli-Bois', 'Bruxelles', 'brussel', 'Rue Balis, 2, 1150 Bruxelles', 'a30@fbfp.be'),
  ('PC Caramboul', 'Bierghes', 'waals-brabant', 'Chaussée Maïeur Habils,145, 1430 Bierghes', 'a31@fbfp.be'),
  ('PC Le Silence', 'Bruxelles', 'brussel', 'Boulodrome Ch. PICQUE - rue de l''Hôtel des Monnaies, 108, 1060 Bruxelles', 'a33@fbfp.be'),
  ('Royal Petanque Club De Rivieren', 'Ganshoren', 'brussel', 'rue au bois, 14, 1083 Ganshoren', 'a34@fbfp.be'),
  ('ASBL Petanque Club De Genappe', 'Genappe', 'waals-brabant', 'rue de Ways, 115z, 1470 Genappe', 'a35@fbfp.be'),
  ('Royal Cp Limaloise', 'Limal', 'waals-brabant', 'Rue Bois l''Abbé, 7, 1300 Limal', 'a37@fbfp.be'),
  ('Royal PC Elite', 'Bruxelles', 'brussel', 'Rue Saint Lambert, 34, 1200 Bruxelles', 'a39@fbfp.be'),
  ('PC Etterbeekois', 'Etterbeek', 'brussel', 'Rue Général Tombeur, 53, 1040 Etterbeek', 'a40@fbfp.be'),
  ('Royal PC Cite Modele', 'Bruxelles', 'brussel', 'Allée de l''Amethyste, 6B, 1020 Bruxelles', 'a43@fbfp.be'),
  ('Pachy PC', 'Waterloo', 'waals-brabant', 'Rue Théophile Delbar, 33/4, 1410 Waterloo', 'a44@fbfp.be'),
  ('Petanque Club Saint-Gillois', 'St-Gilles', 'brussel', 'rue de l''Hôtel des Monnaies, 108, 1060 St-Gilles', 'a46@fbfp.be'),
  ('PC New F.e.s.', 'Bruxelles', 'brussel', 'Rue des Deux Maisons, 34-36, 1140 Bruxelles', 'a47@fbfp.be'),
  ('P.c. Beyne', 'Beyne-Heusay', 'luik', 'rue Victor Yansenne, 2, 4610 Beyne-Heusay', 'b03@fbfp.be'),
  ('Marius Petank''S Club Omal', 'Omal', 'luik', 'rue Jules Stiernet, 82, 4252 Omal', 'b04@fbfp.be'),
  ('Pétanque Club  La Boule Vottemoise D''Herstal', 'Herstal', 'luik', 'rue Haute Marexhe, 142, 4040 Herstal', 'b05@fbfp.be'),
  ('Royal Petanque Club Embourg', 'Embourg', 'luik', 'rue des Coquelicots, 2, 4053 Embourg', 'b06@fbfp.be'),
  ('PC Esneux', 'Esneux', 'luik', 'rue d''Evieux, 51, 4130 Esneux', 'b08@fbfp.be'),
  ('La Boule D''Aaz De Haccourt', 'Haccourt', 'luik', 'rue des 7 Bonniers, 25, 4684 Haccourt', 'b09@fbfp.be'),
  ('PC Boulewanis', 'Waremme', 'luik', 'Rue du Brouck, 12, 4300 Waremme', 'b10@fbfp.be'),
  ('PC Tivoli - Herbesthal', 'Herbesthal', 'luik', 'rue de la Gare, 20, 4710 Herbesthal', 'b11@fbfp.be'),
  ('PC Sprimont', 'Sprimont', 'luik', 'rue Neronry, 21, 4140 Sprimont', 'b12@fbfp.be'),
  ('Bon Accueil Seresien', 'Seraing', 'luik', 'rue Colson, 29, 4100 Seraing', 'b13@fbfp.be'),
  ('Les Cigales De Boncelles', 'Beyne-Heusay', 'luik', 'rue Victor Yansenne, 4510 Beyne-Heusay', 'b14@fbfp.be'),
  ('Petanque New Esneux', 'Esneux', 'luik', 'rue d''Evieux, 51, 4130 Esneux', 'b15@fbfp.be'),
  ('Lam''S PC Forever', 'Haccourt', 'luik', 'rue des 7 Bonniers, 25, 4684 Haccourt', 'b16@fbfp.be'),
  ('PC Malmedy', 'Malmedy', 'luik', 'rue Frédéric Lang, 4960 Malmedy', 'b17@fbfp.be'),
  ('La Fanny Visetoise', 'Vise', 'luik', 'Porte de Souvré, 18, 4600 Vise', 'b20@fbfp.be'),
  ('La Blegnytoise', 'Barchon', 'luik', 'rue d''El Potale, 42, 4671 Barchon', 'b21@fbfp.be'),
  ('C.p.g.h.', 'Grâce-Hollogne', 'luik', 'rue Adrien Materne, 80, 4460 Grâce-Hollogne', 'b22@fbfp.be'),
  ('Royale Petanque Hutoise', 'Huy', 'luik', 'rue de la Campagne, 36, 4500 Huy', 'b23@fbfp.be'),
  ('PC La Romseenne', 'Romsee', 'luik', 'Avenue Thomas Leclercq, 28b, 4624 Romsee', 'b26@fbfp.be'),
  ('PC Oreye', 'Oreye', 'luik', 'Grand Route, 132/4, 4360 Oreye', 'b27@fbfp.be'),
  ('Royal PC Wanze', 'Wanze', 'luik', 'rue Arthur Galand, 26a, 4520 Wanze', 'b30@fbfp.be'),
  ('La Fanny Pepinster', 'Pepinster', 'luik', 'rue Jean Simon, 9, 4860 Pepinster', 'b34@fbfp.be'),
  ('Le Carreau Hannutois', 'Hannut', 'luik', 'rue Lambert Mottart, 21, 4280 Hannut', 'b37@fbfp.be'),
  ('PC Mabotte', 'Jemeppe Sur Meuse', 'luik', 'rue Waleffe, 86, 4101 Jemeppe Sur Meuse', 'b40@fbfp.be'),
  ('PC Moha', 'Moha', 'luik', 'rue des Bruyères, 500a, 4520 Moha', 'b41@fbfp.be'),
  ('Royal Petanque Club La Moisson', 'Beyne-Heusay', 'luik', 'rue Victor Yansenne, 2, 4610 Beyne-Heusay', 'b43@fbfp.be'),
  ('Les Boutons D''Or', 'Flemalle', 'luik', 'rue du Beau Site, 25, 4400 Flemalle', 'b45@fbfp.be'),
  ('Le Muguet Laminois', 'Remicourt', 'luik', 'rue de la Victoire, 64, 4350 Remicourt', 'b49@fbfp.be'),
  ('Royal Petanque Club Saint-Servais', 'Saint-Servais', 'namen', 'Rue du Beau-Vallon, 162, 5002 Saint-Servais', 'd02@fbfp.be'),
  ('Royal Pitchoun Petanque Club ASBL', 'Jambes', 'namen', 'rue Baivy, 26/28, 5100 Jambes', 'd03@fbfp.be'),
  ('New PC Velainois', 'Velaine-Sur-Sambre', 'namen', 'rue Jules Destrée, 19, 5060 Velaine-Sur-Sambre', 'd04@fbfp.be'),
  ('Petanque Club Tamines Sambre', 'Tamines', 'namen', 'rue de l''Ecluse, 1/A, 5060 Tamines', 'd05@fbfp.be'),
  ('Le Cochonnet Mosan', 'Dinant', 'namen', 'Avenue des Combattants, 5500 Dinant', 'd06@fbfp.be'),
  ('PC Les Crayas', 'Nismes', 'namen', 'Parc communal de Nismes , 1, 5670 Nismes', 'd07@fbfp.be'),
  ('ASBL Petanque Beauraing', 'Baronville', 'namen', 'rue Lieutenant Tholomé, 23 Bte 35, 5570 Baronville', 'd08@fbfp.be'),
  ('La Fanny Nismoise', 'Nismes', 'namen', 'Parc communal, 5670 Nismes', 'd18@fbfp.be'),
  ('La Mechoise', 'Meix-Devant-Virton', 'luxemburg', 'rue de Launoy, 6769 Meix-Devant-Virton', 'e01@fbfp.be'),
  ('PC Gouvy', 'Gouvy', 'luxemburg', 'rue d''Houffalize, 22, 6670 Gouvy', 'e02@fbfp.be'),
  ('La Boule Bastognarde', 'Bastogne', 'luxemburg', 'Rue de la Californie, 42, 6600 Bastogne', 'e03@fbfp.be'),
  ('PC Saint-Hubert', 'Saint-Hubert', 'luxemburg', 'Avenue des Chasseurs Ardennais, 7, 6870 Saint-Hubert', 'e04@fbfp.be'),
  ('Les 3 Frontieres Longeau', 'Longeau', 'luxemburg', 'rue d''Athus, 8, 6780 Longeau', 'e05@fbfp.be'),
  ('Royal PC Aubange', 'Aubange', 'luxemburg', 'Rue du Stade, 6790 Aubange', 'e06@fbfp.be'),
  ('Arel Boules Club', 'Arlon', 'luxemburg', 'La Cova - Chemin de la Hart, 6700 Arlon', 'e07@fbfp.be'),
  ('PC Val D''Attert', 'Attert', 'luxemburg', 'Voie de la Liberté, 115, 6717 Attert', 'e08@fbfp.be'),
  ('Abc Durbuy PC', 'Durbuy-Bohon', 'luxemburg', 'Fond Sainte-Anne, 3, 6940 Durbuy-Bohon', 'e09@fbfp.be'),
  ('PC Lhomme', 'Jemelle', 'luxemburg', 'Rue de la Lhomme, 53E, 5580 Jemelle', 'e10@fbfp.be'),
  ('PC Rochefortois', 'Jemelle', 'luxemburg', 'Rue de la Lhomme, 53E, 5580 Jemelle', 'e11@fbfp.be'),
  ('La Boule Feodale Latour', 'Latour', 'luxemburg', 'Rue Baillet-Latour , 26A, 6761 Latour', 'e12@fbfp.be'),
  ('Royal PC Les Carolos', 'Lodelinsart', 'henegouwen', 'Rue du Chemin Vert ,125B, 6042 Lodelinsart', 'h01@fbfp.be'),
  ('Royal Petanque Club  Marcinelle', 'Marcinelle', 'henegouwen', 'Av. Eugène Mascaux, 879, 6001 Marcinelle', 'h02@fbfp.be'),
  ('Climbia''S La Ruche', 'Jumet', 'henegouwen', 'Rue Puissant (face au n° 24), 6040 Jumet', 'h03@fbfp.be'),
  ('La Fanny Bivort', 'Fontaine L''Evêque', 'henegouwen', 'rue de Forchies, 14, 6140 Fontaine L''Evêque', 'h04@fbfp.be'),
  ('Petanque Club Les Marsupilamis', 'Sautin', 'henegouwen', 'rue de Sourenne, 9A, 6470 Sautin', 'h05@fbfp.be'),
  ('Ernelle Monceau', 'Monceau', 'henegouwen', 'rue Albert Camus, 20, 6031 Monceau', 'h06@fbfp.be'),
  ('PC La Botte', 'Momignies', 'henegouwen', 'rue de la Gendarmerie, 1, 6590 Momignies', 'h07@fbfp.be'),
  ('La Petanque Montoise', 'Mons', 'henegouwen', 'rue de la Boulangerie, 2, 7000 Mons', 'h08@fbfp.be'),
  ('PC Au Boule''O', 'Haine-Saint-Pierre', 'henegouwen', 'Chaussée de Jolimont, 50, 7100 Haine-Saint-Pierre', 'h09@fbfp.be'),
  ('Petanque Frasnoise', 'Les Bons Villiers', 'henegouwen', 'rue Jean-Baptiste Loriaux, 3A, 6210 Les Bons Villiers', 'h10@fbfp.be'),
  ('PC Le Pays Noir Farciennes', 'Pironchamps', 'henegouwen', 'rue Centrale, 45, 6240 Pironchamps', 'h11@fbfp.be'),
  ('PC Lutosa', 'Leuze-En-Hainaut', 'henegouwen', 'Avenue des Sports, 1, 7900 Leuze-En-Hainaut', 'h12@fbfp.be'),
  ('Kiki Leval PC', 'Leval-Chaudeville', 'henegouwen', 'rue Jean Leroy, 1, 6500 Leval-Chaudeville', 'h14@fbfp.be'),
  ('Petanque Club Le Roux', 'Le Roux', 'henegouwen', 'rue de la Maladrie, 9A, 5070 Le Roux', 'h15@fbfp.be'),
  ('PC Thulisien', 'Thuillies', 'henegouwen', 'Place de Thuillies, 2, 6536 Thuillies', 'h16@fbfp.be'),
  ('Les Boules Noires', 'Gilly', 'henegouwen', 'rue Pont d''Arcole, 65, 6060 Gilly', 'h17@fbfp.be'),
  ('PC Boussu', 'Tertre', 'henegouwen', 'rue Zéphirin Caron, 1, 7333 Tertre', 'h19@fbfp.be'),
  ('PC A.s. Jumet', 'Lodelinsart', 'henegouwen', 'Rue du Chemin Vert, 25B, 6042 Lodelinsart', 'h20@fbfp.be'),
  ('PC Tertre Esperance', 'Tertre', 'henegouwen', 'rue Zéphirin Caron, 1, 7333 Tertre', 'h23@fbfp.be'),
  ('PC Lessines', 'Lessines', 'henegouwen', 'rue du Pont de pierre, 1, 7860 Lessines', 'h26@fbfp.be'),
  ('PC Chatelet', 'Chatelet', 'henegouwen', 'rue de Couillet, 146B, 6200 Chatelet', 'h27@fbfp.be'),
  ('Tournai Petanque Club (tpc)', 'Vezon', 'henegouwen', 'Rue Albert 1er ,112, 7538 Vezon', 'h30@fbfp.be'),
  ('Masice Ravel Petanque', 'Tertre', 'henegouwen', 'rue des Anglais, 12B, 7333 Tertre', 'h32@fbfp.be'),
  ('Les Six Boulettes Elouges', 'Elouges', 'henegouwen', 'Route d''Elouges, 7370 Elouges', 'h33@fbfp.be')
on conflict (lower(naam), lower(gemeente)) do update set
  adres = excluded.adres,
  contact_email = coalesce(excluded.contact_email, clubs.contact_email);
