-- Le Bouliste.be - seed-data
-- Optioneel: vult de database met de toernooien/clubs uit het design-prototype
-- zodat de site meteen gevuld is tijdens ontwikkeling. Veilig om meerdere
-- keren uit te voeren (idempotent via de unieke index op clubs).

insert into clubs (naam, gemeente, provincie, contact_email) values
  ('Bocholter Petanque', 'Bocholt', 'limburg', null),
  ('Interlommel Petanque', 'Lommel', 'limburg', null),
  ('KP Mistral', 'Gent', 'oost-vlaanderen', null),
  ('KPC Alosta', 'Aalst', 'oost-vlaanderen', null),
  ('KPC Schorpioen', 'Zottegem', 'oost-vlaanderen', null),
  ('KPC Verbroedering', 'Sint-Niklaas', 'oost-vlaanderen', null),
  ('Lommel PC', 'Lommel', 'limburg', null),
  ('Oostendse PC', 'Oostende', 'west-vlaanderen', null),
  ('PC Beersel', 'Beersel', 'vlaams-brabant', null),
  ('PC Bernardus', 'Antwerpen', 'antwerpen', null),
  ('PC Boekt', 'Boechout', 'antwerpen', null),
  ('PC Chapoo', 'Antwerpen', 'antwerpen', null),
  ('PC De Berk', 'Antwerpen', 'antwerpen', null),
  ('PC De Evers', 'Antwerpen', 'antwerpen', null),
  ('PC De Gulden Kamer', 'Antwerpen', 'antwerpen', null),
  ('PC De Lindepet', 'Antwerpen', 'antwerpen', null),
  ('PC De Nete', 'Lier', 'antwerpen', null),
  ('PC De Vuurtoren', 'Nieuwpoort', 'west-vlaanderen', null),
  ('PC De Zeemeermin', 'Blankenberge', 'west-vlaanderen', null),
  ('PC Den Akker', 'Antwerpen', 'antwerpen', null),
  ('PC Dilbeek', 'Dilbeek', 'vlaams-brabant', null),
  ('PC Genenbos', 'Genk', 'limburg', null),
  ('PC Gullegem', 'Wevelgem', 'west-vlaanderen', null),
  ('PC Haeseveld', 'Zottegem', 'oost-vlaanderen', null),
  ('PC Hap Asse', 'Asse', 'vlaams-brabant', null),
  ('PC Hemelhof', 'Antwerpen', 'antwerpen', null),
  ('PC Herentals', 'Herentals', 'antwerpen', null),
  ('PC Kalmthout', 'Kalmthout', 'antwerpen', null),
  ('PC Kelchteren', 'Houthalen-Helchteren', 'limburg', null),
  ('PC Kontich', 'Kontich', 'antwerpen', null),
  ('PC Lier', 'Lier', 'antwerpen', null),
  ('PC Lint', 'Lint', 'antwerpen', null),
  ('PC Maaseik', 'Maaseik', 'limburg', null),
  ('PC Meerosa', 'Rijkevorsel', 'antwerpen', null),
  ('PC Mol', 'Mol', 'antwerpen', null),
  ('PC Niel', 'Niel', 'antwerpen', null),
  ('PC Okapi', 'Antwerpen', 'antwerpen', null),
  ('PC Olympia', 'Antwerpen', 'antwerpen', null),
  ('PC Reynaert', 'Sint-Niklaas', 'oost-vlaanderen', null),
  ('PC Rode', 'Sint-Genesius-Rode', 'vlaams-brabant', null),
  ('PC Rozemaai', 'Antwerpen', 'antwerpen', null),
  ('PC Singel', 'Antwerpen', 'antwerpen', null),
  ('PC Sparrendal', 'Kalmthout', 'antwerpen', null),
  ('PC Terbiest', 'Zaventem', 'vlaams-brabant', null),
  ('PC Terheiden', 'Antwerpen', 'antwerpen', null),
  ('PC Verbroedering', 'Zottegem', 'oost-vlaanderen', null),
  ('PC Wemmel', 'Wemmel', 'vlaams-brabant', null),
  ('PC Zig Zag', 'Antwerpen', 'antwerpen', null),
  ('Pelter PC', 'Pelt', 'limburg', null),
  ('PK De Evers', 'Antwerpen', 'antwerpen', null),
  ('VBBH - Gooik', 'Gooik', 'vlaams-brabant', null)
on conflict (lower(naam), lower(gemeente)) do nothing;

-- Toernooien (jaar 2026, zoals in het prototype). contact_email is een
-- placeholder omdat het prototype dit veld niet toont.
insert into toernooien
  (datum, uur, clubnaam, naam_nl, naam_fr, gemeente, provincie, categorie, formule, aantal_ronden, contact_email, status)
values
  ('2026-07-01', '14:30', 'KPC Schorpioen', 'Zomercircuit 50+ OVL - 4', 'Circuit ete 50+ FLO - 4', 'Zottegem', 'oost-vlaanderen', 'circuit', 'doublette', 3, 'info@kpcschorpioen.be', 'goedgekeurd'),
  ('2026-07-02', '13:30', 'PC Beersel', 'Zomercircuit 50+ VBBH', 'Circuit ete 50+ VBBH', 'Beersel', 'vlaams-brabant', 'circuit', 'doublette', 3, 'info@pcbeersel.be', 'goedgekeurd'),
  ('2026-07-02', '13:30', 'PC De Vuurtoren', 'Zomercircuit 50+ WVL', 'Circuit ete 50+ FLOcc', 'Nieuwpoort', 'west-vlaanderen', 'circuit', 'doublette', 3, 'info@pcdevuurtoren.be', 'goedgekeurd'),
  ('2026-07-04', '13:30', 'PC Genenbos', 'Zomertornooi doublet H/HG', 'Tournoi ete doublette H/HG', 'Genk', 'limburg', 'heren', 'doublette', 4, 'info@pcgenenbos.be', 'goedgekeurd'),
  ('2026-07-04', '14:00', 'KPC Schorpioen', 'Zomertornooi doublet H/HG', 'Tournoi ete doublette H/HG', 'Zottegem', 'oost-vlaanderen', 'heren', 'doublette', 4, 'info@kpcschorpioen.be', 'goedgekeurd'),
  ('2026-07-05', '09:30', 'Oostendse PC', 'Sextet alle categorieen', 'Sextet toutes categories', 'Oostende', 'west-vlaanderen', 'mix', 'sextet', 6, 'info@oostendsepc.be', 'goedgekeurd'),
  ('2026-07-05', '13:30', 'PC Genenbos', 'Zomertornooi doublet D-H', 'Tournoi ete doublette D-H', 'Genk', 'limburg', 'dames', 'doublette', 4, 'info@pcgenenbos.be', 'goedgekeurd'),
  ('2026-07-05', '14:00', 'KP Mistral', 'Zomertornooi doublet H/HG', 'Tournoi ete doublette H/HG', 'Gent', 'oost-vlaanderen', 'heren', 'doublette', 4, 'info@kpmistral.be', 'goedgekeurd'),
  ('2026-07-08', '13:30', 'PC Boekt', 'Trofee 50+ LIM - 5', 'Trophee 50+ LIM - 5', 'Boechout', 'limburg', 'circuit', 'doublette', 3, 'info@pcboekt.be', 'goedgekeurd'),
  ('2026-07-08', '13:30', 'PC Hemelhof', 'Zomercircuit 50+ ANT', 'Circuit ete 50+ ANV', 'Antwerpen', 'antwerpen', 'circuit', 'doublette', 3, 'info@pchemelhof.be', 'goedgekeurd'),
  ('2026-07-08', '14:30', 'KPC Verbroedering', 'Zomercircuit 50+ OVL - 5', 'Circuit ete 50+ FLO - 5', 'Zottegem', 'oost-vlaanderen', 'circuit', 'doublette', 3, 'info@kpcverbroedering.be', 'goedgekeurd'),
  ('2026-07-11', '09:30', 'PC Singel', 'Sextettentornooi (min. 1 dame)', 'Tournoi sextet (min. 1 dame)', 'Antwerpen', 'antwerpen', 'mix', 'sextet', 6, 'info@pcsingel.be', 'goedgekeurd'),
  ('2026-07-11', '13:00', 'PC De Nete', 'Orchideeen Triplet', 'Triplette Orchidees', 'Lier', 'antwerpen', 'heren', 'triplette', 3, 'info@pcdenete.be', 'goedgekeurd'),
  ('2026-07-11', '13:30', 'PC Sparrendal', 'Zomertornooi doublet H/HG', 'Tournoi ete doublette H/HG', 'Kalmthout', 'antwerpen', 'heren', 'doublette', 4, 'info@pcsparrendal.be', 'goedgekeurd'),
  ('2026-07-11', '14:00', 'PC Haeseveld', 'Zomertornooi doublet H/HG', 'Tournoi ete doublette H/HG', 'Zottegem', 'oost-vlaanderen', 'heren', 'doublette', 4, 'info@pchaeseveld.be', 'goedgekeurd'),
  ('2026-07-12', '11:00', 'VBBH - Gooik', 'Open Beachtornooi - Doublet', 'Tournoi plage ouvert - doublette', 'Gooik', 'vlaams-brabant', 'heren', 'doublette', 4, 'info@vbbhgooik.be', 'goedgekeurd'),
  ('2026-07-12', '13:30', 'PC Sparrendal', 'Zomertornooi doublet D-H', 'Tournoi ete doublette D-H', 'Kalmthout', 'antwerpen', 'dames', 'doublette', 4, 'info@pcsparrendal.be', 'goedgekeurd'),
  ('2026-07-18', '10:00', 'PC Rozemaai', 'Fruittornooi', 'Tournoi des fruits', 'Antwerpen', 'antwerpen', 'heren', 'doublette', 5, 'info@pcrozemaai.be', 'goedgekeurd'),
  ('2026-07-18', '10:00', 'PC Reynaert', 'Sextet', 'Sextet', 'Sint-Niklaas', 'oost-vlaanderen', 'heren', 'sextet', 4, 'info@pcreynaert.be', 'goedgekeurd'),
  ('2026-07-18', '13:00', 'Oostendse PC', 'Grote Prijs Oostende - Triplet 1D + 2H', 'Grand Prix Ostende - Triplette 1D + 2H', 'Oostende', 'west-vlaanderen', 'dames', 'triplette', 4, 'info@oostendsepc.be', 'goedgekeurd'),
  ('2026-07-18', '13:30', 'PC Singel', 'Open tornooi triplet (Veldkant)', 'Tournoi ouvert triplette (Veldkant)', 'Antwerpen', 'antwerpen', 'heren', 'triplette', 4, 'info@pcsingel.be', 'goedgekeurd'),
  ('2026-07-18', '13:30', 'Bocholter Petanque', 'Zomertornooi doublet H/HG', 'Tournoi ete doublette H/HG', 'Bocholt', 'limburg', 'heren', 'doublette', 4, 'info@bocholterpetanque.be', 'goedgekeurd'),
  ('2026-07-19', '13:30', 'Bocholter Petanque', 'Zomertornooi doublet D-H', 'Tournoi ete doublette D-H', 'Bocholt', 'limburg', 'dames', 'doublette', 4, 'info@bocholterpetanque.be', 'goedgekeurd'),
  ('2026-07-21', '11:00', 'PC Boekt', 'Kwintet H/HG', 'Quintette H/HG', 'Boechout', 'antwerpen', 'mix', 'kwintet', 5, 'info@pcboekt.be', 'goedgekeurd'),
  ('2026-07-21', '14:00', 'KP Mistral', 'Gentse Feesten - doublet H/HG', 'Fetes de Gand - doublette H/HG', 'Gent', 'oost-vlaanderen', 'heren', 'doublette', 4, 'info@kpmistral.be', 'goedgekeurd'),
  ('2026-07-21', '14:00', 'KP Mistral', 'Gentse Feesten - doublet dames', 'Fetes de Gand - doublette dames', 'Gent', 'oost-vlaanderen', 'dames', 'doublette', 4, 'info@kpmistral.be', 'goedgekeurd'),
  ('2026-07-26', '11:00', 'PC Bernardus', 'Doublet', 'Doublette', 'Antwerpen', 'antwerpen', 'heren', 'doublette', 4, 'info@pcbernardus.be', 'goedgekeurd'),
  ('2026-07-26', '13:30', 'KP Mistral', 'Kwartet 50+ - 1 dame verplicht', 'Quartet 50+ - 1 dame obligatoire', 'Gent', 'oost-vlaanderen', 'mix', 'quartet', 4, 'info@kpmistral.be', 'goedgekeurd'),
  ('2026-08-01', '11:00', 'PC Lint', 'Kleurentornooi', 'Tournoi couleurs', 'Lint', 'antwerpen', 'mix', 'kleurentornooi', 1, 'info@pclint.be', 'goedgekeurd'),
  ('2026-08-01', '13:00', 'PC Haeseveld', 'Memorial Van Rumst - Kleurentornooi', 'Memorial Van Rumst - Tournoi couleurs', 'Zottegem', 'oost-vlaanderen', 'heren', 'kleurentornooi', 4, 'info@pchaeseveld.be', 'goedgekeurd'),
  ('2026-08-02', '11:00', 'PC Kalmthout', 'Beach Petanque doublet', 'Petanque plage doublette', 'Kalmthout', 'antwerpen', 'heren', 'doublette', 4, 'info@pckalmthout.be', 'goedgekeurd'),
  ('2026-08-02', '13:30', 'PC Boekt', 'Zomertornooi doublet D-H', 'Tournoi ete doublette D-H', 'Boechout', 'antwerpen', 'dames', 'doublette', 4, 'info@pcboekt.be', 'goedgekeurd'),
  ('2026-08-02', '13:30', 'PC Terheiden', 'Kip en ei tornooi - Triplet 2H+1D', 'Tournoi poule et oeuf - Triplette 2H+1D', 'Antwerpen', 'antwerpen', 'mix', 'triplette', 4, 'info@pcterheiden.be', 'goedgekeurd'),
  ('2026-08-05', '09:30', 'Pelter PC', 'PKD 50+ Limburg', 'PKD 50+ Limbourg', 'Pelt', 'limburg', 'circuit', 'doublette', 5, 'info@pelterpc.be', 'goedgekeurd'),
  ('2026-08-08', '10:00', 'PK De Evers', 'Sextet - 1 dame', 'Sextet - 1 dame', 'Antwerpen', 'antwerpen', 'mix', 'sextet', 4, 'info@pkdeevers.be', 'goedgekeurd'),
  ('2026-08-08', '13:30', 'PC Maaseik', 'Maaseiker weekend doublet H/HG', 'Weekend Maaseik doublette H/HG', 'Maaseik', 'limburg', 'heren', 'doublette', 4, 'info@pcmaaseik.be', 'goedgekeurd'),
  ('2026-08-09', '14:00', 'KP Mistral', 'Doublet 1 dame + 1 heer', 'Doublette 1 dame + 1 homme', 'Gent', 'oost-vlaanderen', 'dames', 'doublette', 4, 'info@kpmistral.be', 'goedgekeurd'),
  ('2026-08-15', '13:00', 'Oostendse PC', 'Mini maxi - 1 volw + 1 jeugd onder 16 jaar', 'Mini maxi - 1 adulte + 1 jeune -16 ans', 'Oostende', 'west-vlaanderen', 'jeugd', 'doublette', 4, 'info@oostendsepc.be', 'goedgekeurd'),
  ('2026-08-15', '13:00', 'Oostendse PC', 'Doublet dames', 'Doublette dames', 'Oostende', 'west-vlaanderen', 'dames', 'doublette', 4, 'info@oostendsepc.be', 'goedgekeurd'),
  ('2026-08-16', '14:00', 'PC Haeseveld', 'Triplet dames', 'Triplette dames', 'Zottegem', 'oost-vlaanderen', 'dames', 'triplette', 4, 'info@pchaeseveld.be', 'goedgekeurd'),
  ('2026-08-19', '10:00', 'PC Kelchteren', 'Sextet 50+ H/HG - 3', 'Sextet 50+ H/HG - 3', 'Houthalen-Helchteren', 'limburg', 'circuit', 'sextet', 6, 'info@pckelchteren.be', 'goedgekeurd'),
  ('2026-08-22', '09:00', 'PC Kelchteren', '10u "Toon Lemmens" - doublet H/HG', '10h "Toon Lemmens" - doublette H/HG', 'Houthalen-Helchteren', 'limburg', 'kampioenschap', 'doublette', 8, 'info@pckelchteren.be', 'goedgekeurd'),
  ('2026-08-22', '10:00', 'PC Herentals', 'Kruiskensberg doublet', 'Doublette Kruiskensberg', 'Herentals', 'antwerpen', 'heren', 'doublette', 5, 'info@pcherentals.be', 'goedgekeurd'),
  ('2026-08-22', '11:00', 'PC Singel', 'Van Malder Open (doublet)', 'Van Malder Open (doublette)', 'Antwerpen', 'antwerpen', 'heren', 'doublette', 4, 'info@pcsingel.be', 'goedgekeurd'),
  ('2026-08-22', '13:00', 'PC Verbroedering', 'Tornooi Ronny Depaepe - H/HG Doublet', 'Tournoi Ronny Depaepe - H/HG Doublette', 'Zottegem', 'oost-vlaanderen', 'heren', 'doublette', 4, 'info@pcverbroedering.be', 'goedgekeurd'),
  ('2026-08-23', '13:30', 'KP Mistral', 'Kwartet - 2 dames verplicht', 'Quartet - 2 dames obligatoires', 'Gent', 'oost-vlaanderen', 'mix', 'quartet', 4, 'info@kpmistral.be', 'goedgekeurd'),
  ('2026-08-29', '09:30', 'Oostendse PC', 'Open tornooi Naim Khirat - triplet', 'Tournoi ouvert Naim Khirat - triplette', 'Oostende', 'west-vlaanderen', 'heren', 'triplette', 4, 'info@oostendsepc.be', 'goedgekeurd'),
  ('2026-08-29', '13:30', 'Interlommel Petanque', 'Dames- en herenontmoeting', 'Rencontre dames et messieurs', 'Lommel', 'limburg', 'dames', 'doublette', 4, 'info@interlommelpetanque.be', 'goedgekeurd'),
  ('2026-08-30', '14:00', 'PC Haeseveld', 'Mem. De Vetter-Bayens-Bambust - doublet H/HG', 'Mem. De Vetter-Bayens-Bambust - doublette H/HG', 'Zottegem', 'oost-vlaanderen', 'heren', 'doublette', 4, 'info@pchaeseveld.be', 'goedgekeurd'),
  ('2026-09-05', '10:00', 'PC Verbroedering', 'Sextet - 2 dames verplicht', 'Sextet - 2 dames obligatoires', 'Zottegem', 'oost-vlaanderen', 'heren', 'sextet', 4, 'info@pcverbroedering.be', 'goedgekeurd'),
  ('2026-09-05', '10:30', 'PC Kontich', 'Dames doublet', 'Doublette dames', 'Kontich', 'antwerpen', 'dames', 'doublette', 4, 'info@pckontich.be', 'goedgekeurd'),
  ('2026-09-12', '10:00', 'PC De Lindepet', 'Mastentoptornooi doublet', 'Tournoi Mastentop doublette', 'Antwerpen', 'antwerpen', 'kampioenschap', 'doublette', 5, 'info@pcdelindepet.be', 'goedgekeurd'),
  ('2026-09-13', '13:30', 'PC Olympia', 'Zomertornooi doublet D-H', 'Tournoi ete doublette D-H', 'Antwerpen', 'antwerpen', 'dames', 'doublette', 4, 'info@pcolympia.be', 'goedgekeurd'),
  ('2026-09-18', '10:00', 'PC Boekt', 'Eindronde 50+', 'Finale 50+', 'Boechout', 'antwerpen', 'kampioenschap', 'doublette', 4, 'info@pcboekt.be', 'goedgekeurd'),
  ('2026-09-19', '13:00', 'PC Haeseveld', 'Triplet H/HG', 'Triplette H/HG', 'Zottegem', 'oost-vlaanderen', 'heren', 'triplette', 4, 'info@pchaeseveld.be', 'goedgekeurd'),
  ('2026-09-20', '11:00', 'PC Bernardus', 'Triplet', 'Triplette', 'Antwerpen', 'antwerpen', 'heren', 'triplette', 4, 'info@pcbernardus.be', 'goedgekeurd'),
  ('2026-09-26', '10:00', 'PC Haeseveld', 'Memorial Dassonville - doublet H/HG', 'Memorial Dassonville - doublette H/HG', 'Zottegem', 'oost-vlaanderen', 'kampioenschap', 'doublette', 4, 'info@pchaeseveld.be', 'goedgekeurd'),
  ('2026-09-26', '13:30', 'PC Singel', 'Recreantentornooi doublet', 'Tournoi loisir doublette', 'Antwerpen', 'antwerpen', 'heren', 'doublette', 4, 'info@pcsingel.be', 'goedgekeurd');
